//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApMaterno {
            get {
                return this.ApMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApMaternoField, value) != true)) {
                    this.ApMaternoField = value;
                    this.RaisePropertyChanged("ApMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApPaterno {
            get {
                return this.ApPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApPaternoField, value) != true)) {
                    this.ApPaternoField = value;
                    this.RaisePropertyChanged("ApPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServicio")]
    public interface IServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarPersonas", ReplyAction="http://tempuri.org/IServicio/ListarPersonasResponse")]
        WebApplication1.ServiceReference1.Persona[] ListarPersonas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ListarPersonas", ReplyAction="http://tempuri.org/IServicio/ListarPersonasResponse")]
        System.Threading.Tasks.Task<WebApplication1.ServiceReference1.Persona[]> ListarPersonasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/InsertarPersonas", ReplyAction="http://tempuri.org/IServicio/InsertarPersonasResponse")]
        bool InsertarPersonas(string ApPaterno, string ApMaterno, string Nombre, bool Estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/InsertarPersonas", ReplyAction="http://tempuri.org/IServicio/InsertarPersonasResponse")]
        System.Threading.Tasks.Task<bool> InsertarPersonasAsync(string ApPaterno, string ApMaterno, string Nombre, bool Estado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioChannel : WebApplication1.ServiceReference1.IServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClient : System.ServiceModel.ClientBase<WebApplication1.ServiceReference1.IServicio>, WebApplication1.ServiceReference1.IServicio {
        
        public ServicioClient() {
        }
        
        public ServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplication1.ServiceReference1.Persona[] ListarPersonas() {
            return base.Channel.ListarPersonas();
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ServiceReference1.Persona[]> ListarPersonasAsync() {
            return base.Channel.ListarPersonasAsync();
        }
        
        public bool InsertarPersonas(string ApPaterno, string ApMaterno, string Nombre, bool Estado) {
            return base.Channel.InsertarPersonas(ApPaterno, ApMaterno, Nombre, Estado);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarPersonasAsync(string ApPaterno, string ApMaterno, string Nombre, bool Estado) {
            return base.Channel.InsertarPersonasAsync(ApPaterno, ApMaterno, Nombre, Estado);
        }
    }
}
