//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcVenta.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;
    public partial class TB_PRUEBA
    {
        [Key]
        public int COD_PRUEBA { get; set; }
        public string DES_PRUEBA { get; set; }
        public string DAT_PRUEBA { get; set; }
    }
}
